import = [
  # uncomment the flavour you want below:
  #"~/.config/alacritty/catppuccin-latte.toml"
  # "~/.config/alacritty/catppuccin-frappe.toml"
  "~/.config/alacritty/catppuccin-macchiato.toml"
  # "~/.config/alacritty/catppuccin-mocha.toml"
]

# [window]
# option_as_alt = "OnlyLeft"

[font]
size = 16.0

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[env]
TERM = "xterm-256color"

[keyboard]
bindings = [
{ key = "<", mods = "Command|Shift", chars = "\u001b<" },
{ key = ">", mods = "Command|Shift", chars = "\u001b>" },
{ key = "Comma", mods = "Command", chars = "\u001b," },
{ key = "Period", mods = "Command", chars = "\u001b." },


]

  # - { key: Period,   mods: Alt|Shift, chars: "\x1b>"                       } # Alt + >
  # - { key: Comma,    mods: Alt|Shift, chars: "\x1b<"                       } # Alt + <
